//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipp.RecruitmentTest.IPaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPaymentService.IPaymentService")]
    public interface IPaymentService {
        
        // CODEGEN: Generating message contract since element name WhatsYourIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WhatsYourId", ReplyAction="*")]
        Ipp.RecruitmentTest.IPaymentService.WhatsYourIdResponse WhatsYourId(Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequest request);
        
        // CODEGEN: Generating message contract since element name cardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsCardNumberValid", ReplyAction="*")]
        Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidResponse IsCardNumberValid(Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidPaymentAmount", ReplyAction="*")]
        bool IsValidPaymentAmount(long amount);
        
        // CODEGEN: Generating message contract since element name cardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanMakePaymentWithCard", ReplyAction="*")]
        Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardResponse CanMakePaymentWithCard(Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WhatsYourIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WhatsYourId", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequestBody Body;
        
        public WhatsYourIdRequest() {
        }
        
        public WhatsYourIdRequest(Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WhatsYourIdRequestBody {
        
        public WhatsYourIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WhatsYourIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WhatsYourIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.WhatsYourIdResponseBody Body;
        
        public WhatsYourIdResponse() {
        }
        
        public WhatsYourIdResponse(Ipp.RecruitmentTest.IPaymentService.WhatsYourIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WhatsYourIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WhatsYourIdResult;
        
        public WhatsYourIdResponseBody() {
        }
        
        public WhatsYourIdResponseBody(string WhatsYourIdResult) {
            this.WhatsYourIdResult = WhatsYourIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCardNumberValidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCardNumberValid", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequestBody Body;
        
        public IsCardNumberValidRequest() {
        }
        
        public IsCardNumberValidRequest(Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsCardNumberValidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNumber;
        
        public IsCardNumberValidRequestBody() {
        }
        
        public IsCardNumberValidRequestBody(string cardNumber) {
            this.cardNumber = cardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCardNumberValidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCardNumberValidResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidResponseBody Body;
        
        public IsCardNumberValidResponse() {
        }
        
        public IsCardNumberValidResponse(Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsCardNumberValidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsCardNumberValidResult;
        
        public IsCardNumberValidResponseBody() {
        }
        
        public IsCardNumberValidResponseBody(bool IsCardNumberValidResult) {
            this.IsCardNumberValidResult = IsCardNumberValidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanMakePaymentWithCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanMakePaymentWithCard", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequestBody Body;
        
        public CanMakePaymentWithCardRequest() {
        }
        
        public CanMakePaymentWithCardRequest(Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanMakePaymentWithCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int expiryMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int expiryYear;
        
        public CanMakePaymentWithCardRequestBody() {
        }
        
        public CanMakePaymentWithCardRequestBody(string cardNumber, int expiryMonth, int expiryYear) {
            this.cardNumber = cardNumber;
            this.expiryMonth = expiryMonth;
            this.expiryYear = expiryYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanMakePaymentWithCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanMakePaymentWithCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardResponseBody Body;
        
        public CanMakePaymentWithCardResponse() {
        }
        
        public CanMakePaymentWithCardResponse(Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanMakePaymentWithCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CanMakePaymentWithCardResult;
        
        public CanMakePaymentWithCardResponseBody() {
        }
        
        public CanMakePaymentWithCardResponseBody(bool CanMakePaymentWithCardResult) {
            this.CanMakePaymentWithCardResult = CanMakePaymentWithCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : Ipp.RecruitmentTest.IPaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<Ipp.RecruitmentTest.IPaymentService.IPaymentService>, Ipp.RecruitmentTest.IPaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipp.RecruitmentTest.IPaymentService.WhatsYourIdResponse Ipp.RecruitmentTest.IPaymentService.IPaymentService.WhatsYourId(Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequest request) {
            return base.Channel.WhatsYourId(request);
        }
        
        public string WhatsYourId() {
            Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequest inValue = new Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequest();
            inValue.Body = new Ipp.RecruitmentTest.IPaymentService.WhatsYourIdRequestBody();
            Ipp.RecruitmentTest.IPaymentService.WhatsYourIdResponse retVal = ((Ipp.RecruitmentTest.IPaymentService.IPaymentService)(this)).WhatsYourId(inValue);
            return retVal.Body.WhatsYourIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidResponse Ipp.RecruitmentTest.IPaymentService.IPaymentService.IsCardNumberValid(Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequest request) {
            return base.Channel.IsCardNumberValid(request);
        }
        
        public bool IsCardNumberValid(string cardNumber) {
            Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequest inValue = new Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequest();
            inValue.Body = new Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidRequestBody();
            inValue.Body.cardNumber = cardNumber;
            Ipp.RecruitmentTest.IPaymentService.IsCardNumberValidResponse retVal = ((Ipp.RecruitmentTest.IPaymentService.IPaymentService)(this)).IsCardNumberValid(inValue);
            return retVal.Body.IsCardNumberValidResult;
        }
        
        public bool IsValidPaymentAmount(long amount) {
            return base.Channel.IsValidPaymentAmount(amount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardResponse Ipp.RecruitmentTest.IPaymentService.IPaymentService.CanMakePaymentWithCard(Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequest request) {
            return base.Channel.CanMakePaymentWithCard(request);
        }
        
        public bool CanMakePaymentWithCard(string cardNumber, int expiryMonth, int expiryYear) {
            Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequest inValue = new Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequest();
            inValue.Body = new Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardRequestBody();
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.expiryMonth = expiryMonth;
            inValue.Body.expiryYear = expiryYear;
            Ipp.RecruitmentTest.IPaymentService.CanMakePaymentWithCardResponse retVal = ((Ipp.RecruitmentTest.IPaymentService.IPaymentService)(this)).CanMakePaymentWithCard(inValue);
            return retVal.Body.CanMakePaymentWithCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPaymentService.ServiceSoap")]
    public interface ServiceSoap {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Ipp.RecruitmentTest.IPaymentService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Ipp.RecruitmentTest.IPaymentService.ServiceSoap>, Ipp.RecruitmentTest.IPaymentService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPaymentService.ServiceSoap12")]
    public interface ServiceSoap12 {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoap12Channel : Ipp.RecruitmentTest.IPaymentService.ServiceSoap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoap12Client : System.ServiceModel.ClientBase<Ipp.RecruitmentTest.IPaymentService.ServiceSoap12>, Ipp.RecruitmentTest.IPaymentService.ServiceSoap12 {
        
        public ServiceSoap12Client() {
        }
        
        public ServiceSoap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
