//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPaymentServices_Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PaymentGatewaySoap")]
    public interface PaymentGatewaySoap {
        
        // CODEGEN: Generating message contract since element name WhatsYourIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WhatsYourId", ReplyAction="*")]
        IPaymentServices_Tests.ServiceReference1.WhatsYourIdResponse WhatsYourId(IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequest request);
        
        // CODEGEN: Generating message contract since element name cardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsCardNumberValid", ReplyAction="*")]
        IPaymentServices_Tests.ServiceReference1.IsCardNumberValidResponse IsCardNumberValid(IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidPaymentAmount", ReplyAction="*")]
        bool IsValidPaymentAmount(long amount);
        
        // CODEGEN: Generating message contract since element name cardNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanMakePaymentWithCard", ReplyAction="*")]
        IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardResponse CanMakePaymentWithCard(IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WhatsYourIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WhatsYourId", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequestBody Body;
        
        public WhatsYourIdRequest() {
        }
        
        public WhatsYourIdRequest(IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WhatsYourIdRequestBody {
        
        public WhatsYourIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WhatsYourIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WhatsYourIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.WhatsYourIdResponseBody Body;
        
        public WhatsYourIdResponse() {
        }
        
        public WhatsYourIdResponse(IPaymentServices_Tests.ServiceReference1.WhatsYourIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WhatsYourIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WhatsYourIdResult;
        
        public WhatsYourIdResponseBody() {
        }
        
        public WhatsYourIdResponseBody(string WhatsYourIdResult) {
            this.WhatsYourIdResult = WhatsYourIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCardNumberValidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCardNumberValid", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequestBody Body;
        
        public IsCardNumberValidRequest() {
        }
        
        public IsCardNumberValidRequest(IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsCardNumberValidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNumber;
        
        public IsCardNumberValidRequestBody() {
        }
        
        public IsCardNumberValidRequestBody(string cardNumber) {
            this.cardNumber = cardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCardNumberValidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCardNumberValidResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.IsCardNumberValidResponseBody Body;
        
        public IsCardNumberValidResponse() {
        }
        
        public IsCardNumberValidResponse(IPaymentServices_Tests.ServiceReference1.IsCardNumberValidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsCardNumberValidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsCardNumberValidResult;
        
        public IsCardNumberValidResponseBody() {
        }
        
        public IsCardNumberValidResponseBody(bool IsCardNumberValidResult) {
            this.IsCardNumberValidResult = IsCardNumberValidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanMakePaymentWithCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanMakePaymentWithCard", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequestBody Body;
        
        public CanMakePaymentWithCardRequest() {
        }
        
        public CanMakePaymentWithCardRequest(IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanMakePaymentWithCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int expiryMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int expiryYear;
        
        public CanMakePaymentWithCardRequestBody() {
        }
        
        public CanMakePaymentWithCardRequestBody(string cardNumber, int expiryMonth, int expiryYear) {
            this.cardNumber = cardNumber;
            this.expiryMonth = expiryMonth;
            this.expiryYear = expiryYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanMakePaymentWithCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanMakePaymentWithCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardResponseBody Body;
        
        public CanMakePaymentWithCardResponse() {
        }
        
        public CanMakePaymentWithCardResponse(IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanMakePaymentWithCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CanMakePaymentWithCardResult;
        
        public CanMakePaymentWithCardResponseBody() {
        }
        
        public CanMakePaymentWithCardResponseBody(bool CanMakePaymentWithCardResult) {
            this.CanMakePaymentWithCardResult = CanMakePaymentWithCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentGatewaySoapChannel : IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewaySoapClient : System.ServiceModel.ClientBase<IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap>, IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap {
        
        public PaymentGatewaySoapClient() {
        }
        
        public PaymentGatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPaymentServices_Tests.ServiceReference1.WhatsYourIdResponse IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap.WhatsYourId(IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequest request) {
            return base.Channel.WhatsYourId(request);
        }
        
        public string WhatsYourId() {
            IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequest inValue = new IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequest();
            inValue.Body = new IPaymentServices_Tests.ServiceReference1.WhatsYourIdRequestBody();
            IPaymentServices_Tests.ServiceReference1.WhatsYourIdResponse retVal = ((IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap)(this)).WhatsYourId(inValue);
            return retVal.Body.WhatsYourIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPaymentServices_Tests.ServiceReference1.IsCardNumberValidResponse IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap.IsCardNumberValid(IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequest request) {
            return base.Channel.IsCardNumberValid(request);
        }
        
        public bool IsCardNumberValid(string cardNumber) {
            IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequest inValue = new IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequest();
            inValue.Body = new IPaymentServices_Tests.ServiceReference1.IsCardNumberValidRequestBody();
            inValue.Body.cardNumber = cardNumber;
            IPaymentServices_Tests.ServiceReference1.IsCardNumberValidResponse retVal = ((IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap)(this)).IsCardNumberValid(inValue);
            return retVal.Body.IsCardNumberValidResult;
        }
        
        public bool IsValidPaymentAmount(long amount) {
            return base.Channel.IsValidPaymentAmount(amount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardResponse IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap.CanMakePaymentWithCard(IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequest request) {
            return base.Channel.CanMakePaymentWithCard(request);
        }
        
        public bool CanMakePaymentWithCard(string cardNumber, int expiryMonth, int expiryYear) {
            IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequest inValue = new IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequest();
            inValue.Body = new IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardRequestBody();
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.expiryMonth = expiryMonth;
            inValue.Body.expiryYear = expiryYear;
            IPaymentServices_Tests.ServiceReference1.CanMakePaymentWithCardResponse retVal = ((IPaymentServices_Tests.ServiceReference1.PaymentGatewaySoap)(this)).CanMakePaymentWithCard(inValue);
            return retVal.Body.CanMakePaymentWithCardResult;
        }
    }
}
